export const campusMapLocations = [
  {
    "id": "magnolia",
    "officialId": "d719150862544f6385c87129271bdd00",
    "sourceType": "building",
    "name": "白玉兰餐厅",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 65.74,
    "y": 55.622,
    "guide": "白玉兰餐厅，餐饮区。",
    "mapDescription": "白玉兰餐厅，餐饮区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "白玉兰餐厅 餐饮区 餐饮"
  },
  {
    "id": "place-b2f5c7d5",
    "officialId": "b2f5c7d51294404288711fbb6b176905",
    "sourceType": "place",
    "name": "白玉兰一楼学生食堂",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 65.74,
    "y": 55.622,
    "hostBuildingId": "magnolia",
    "hostBuildingName": "白玉兰餐厅",
    "guide": "白玉兰一楼学生食堂，位于或靠近白玉兰餐厅。",
    "mapDescription": "白玉兰一楼学生食堂，位于或靠近白玉兰餐厅；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "白玉兰一楼学生食堂 餐饮区 餐饮 白玉兰餐厅"
  },
  {
    "id": "place-fe2a1ecf",
    "officialId": "fe2a1ecf2ec1414b8d6324bf93fb5f42",
    "sourceType": "place",
    "name": "教工餐厅与点餐区",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 63.764,
    "y": 58.19,
    "hostBuildingId": "magnolia",
    "hostBuildingName": "白玉兰餐厅",
    "guide": "教工餐厅与点餐区，位于或靠近白玉兰餐厅。",
    "mapDescription": "教工餐厅与点餐区，位于或靠近白玉兰餐厅；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "教工餐厅与点餐区 餐饮区 餐饮 白玉兰餐厅"
  },
  {
    "id": "cafe",
    "officialId": "0395352324dd49eaa2595cccc42d8ad8",
    "sourceType": "place",
    "name": "咖啡厅",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 68.793,
    "y": 28.961,
    "hostBuildingId": "dorm-1",
    "hostBuildingName": "学生公寓1号楼",
    "guide": "咖啡厅，位于或靠近学生公寓1号楼。",
    "mapDescription": "咖啡厅，位于或靠近学生公寓1号楼；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "咖啡厅 餐饮区 餐饮 学生公寓1号楼"
  },
  {
    "id": "nice-cafe",
    "officialId": "5149e81e317346adb7f4bd7b108f26d8",
    "sourceType": "place",
    "name": "耐思咖啡",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 70.535,
    "y": 30.574,
    "hostBuildingId": "dorm-1",
    "hostBuildingName": "学生公寓1号楼",
    "guide": "耐思咖啡，位于或靠近学生公寓1号楼。",
    "mapDescription": "耐思咖啡，位于或靠近学生公寓1号楼；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "耐思咖啡 餐饮区 餐饮 学生公寓1号楼"
  },
  {
    "id": "place-604e5cc3",
    "officialId": "604e5cc37ada4cbdbe40aa8783e7d420",
    "sourceType": "place",
    "name": "尚科餐厅",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 66.568,
    "y": 40.815,
    "hostBuildingId": "kfc",
    "hostBuildingName": "KFC",
    "guide": "尚科餐厅，位于或靠近KFC。",
    "mapDescription": "尚科餐厅，位于或靠近KFC；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "尚科餐厅 餐饮区 餐饮 KFC"
  },
  {
    "id": "food-court",
    "officialId": "2376c9073269497c911f0f20fb7ed44b",
    "sourceType": "building",
    "name": "尚科餐厅/西餐厅",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 68.244,
    "y": 44.246,
    "guide": "尚科餐厅/西餐厅，餐饮区。",
    "mapDescription": "尚科餐厅/西餐厅，餐饮区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "尚科餐厅/西餐厅 餐饮区 餐饮"
  },
  {
    "id": "place-fcd6a84e",
    "officialId": "fcd6a84e9af648fdac33832762876cdc",
    "sourceType": "place",
    "name": "尚科餐厅1楼",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 67.635,
    "y": 44.644,
    "hostBuildingId": "food-court",
    "hostBuildingName": "尚科餐厅/西餐厅",
    "guide": "尚科餐厅1楼，位于或靠近尚科餐厅/西餐厅。",
    "mapDescription": "尚科餐厅1楼，位于或靠近尚科餐厅/西餐厅；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "尚科餐厅1楼 餐饮区 餐饮 尚科餐厅/西餐厅"
  },
  {
    "id": "place-9b395957",
    "officialId": "9b3959579a3045f09fc539fc4cd8cf2b",
    "sourceType": "place",
    "name": "尚科餐厅二楼自选区",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 68.358,
    "y": 42.726,
    "hostBuildingId": "food-court",
    "hostBuildingName": "尚科餐厅/西餐厅",
    "guide": "尚科餐厅二楼自选区，位于或靠近尚科餐厅/西餐厅。",
    "mapDescription": "尚科餐厅二楼自选区，位于或靠近尚科餐厅/西餐厅；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "尚科餐厅二楼自选区 餐饮区 餐饮 尚科餐厅/西餐厅"
  },
  {
    "id": "silk-road-dining",
    "officialId": "49c92421fec648beb34c0e15c3097ff2",
    "sourceType": "building",
    "name": "丝路餐厅",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 68.388,
    "y": 30.967,
    "guide": "丝路餐厅，餐饮区。",
    "mapDescription": "丝路餐厅，餐饮区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "丝路餐厅 餐饮区 餐饮"
  },
  {
    "id": "place-82c19dfc",
    "officialId": "82c19dfc151744d49444d437bbe69068",
    "sourceType": "place",
    "name": "丝路餐厅",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 67.044,
    "y": 31.434,
    "hostBuildingId": "silk-road-dining",
    "hostBuildingName": "丝路餐厅",
    "guide": "丝路餐厅，餐饮区。",
    "mapDescription": "丝路餐厅，餐饮区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "丝路餐厅 餐饮区 餐饮 丝路餐厅"
  },
  {
    "id": "place-e3ccaf6b",
    "officialId": "e3ccaf6be0d7452bba494cad47491bb2",
    "sourceType": "place",
    "name": "西餐厅",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 70.297,
    "y": 42.676,
    "hostBuildingId": "dorm-4",
    "hostBuildingName": "学生公寓4号楼",
    "guide": "西餐厅，位于或靠近学生公寓4号楼。",
    "mapDescription": "西餐厅，位于或靠近学生公寓4号楼；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "西餐厅 餐饮区 餐饮 学生公寓4号楼"
  },
  {
    "id": "kfc",
    "officialId": "562411a5007b450f83bbd32602694ffc",
    "sourceType": "building",
    "name": "KFC",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 65.572,
    "y": 39.744,
    "guide": "KFC，餐饮区。",
    "mapDescription": "KFC，餐饮区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "KFC 餐饮区 餐饮"
  },
  {
    "id": "kfc-place",
    "officialId": "241bf2ad2e874050bc54ed49b30607c0",
    "sourceType": "place",
    "name": "KFC",
    "area": "餐饮区",
    "category": "餐饮",
    "x": 66.884,
    "y": 41.202,
    "hostBuildingId": "kfc",
    "hostBuildingName": "KFC",
    "guide": "KFC，餐饮区。",
    "mapDescription": "KFC，餐饮区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "KFC 餐饮区 餐饮 KFC"
  },
  {
    "id": "auditorium",
    "officialId": "cd9d3699e4e849f9a4516121222bde64",
    "sourceType": "building",
    "name": "报告厅",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 54.052,
    "y": 58.912,
    "guide": "报告厅，教学科研区。",
    "mapDescription": "报告厅，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "报告厅 教学科研区 教学科研"
  },
  {
    "id": "sem",
    "officialId": "16b2b62dc8364beaaaa228226788274e",
    "sourceType": "building",
    "name": "创业与管理学院",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 43.181,
    "y": 61.659,
    "guide": "创业与管理学院，教学科研区。",
    "mapDescription": "创业与管理学院，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "创业与管理学院 教学科研区 教学科研"
  },
  {
    "id": "sca",
    "officialId": "0b3d7b25868f41308bbb4a739fd0147b",
    "sourceType": "building",
    "name": "创意与艺术学院",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 31.255,
    "y": 61.002,
    "guide": "创意与艺术学院，教学科研区。",
    "mapDescription": "创意与艺术学院，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "创意与艺术学院 教学科研区 教学科研"
  },
  {
    "id": "teaching",
    "officialId": "edb12f3dec97483791e3d63280b2d22c",
    "sourceType": "building",
    "name": "教学中心",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 47.685,
    "y": 68.061,
    "guide": "教学中心，教学科研区。",
    "mapDescription": "教学中心，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "教学中心 教学科研区 教学科研"
  },
  {
    "id": "ici",
    "officialId": "7a72bc5652354bac92c7bf044d744656",
    "sourceType": "building",
    "name": "免疫化学研究所",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 52.361,
    "y": 11.018,
    "guide": "免疫化学研究所，教学科研区。",
    "mapDescription": "免疫化学研究所，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "免疫化学研究所 教学科研区 教学科研"
  },
  {
    "id": "ihss",
    "officialId": "bb45edc5493c4454af96530515376910",
    "sourceType": "building",
    "name": "人文科学研究院",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 34.288,
    "y": 57.997,
    "guide": "人文科学研究院，教学科研区。",
    "mapDescription": "人文科学研究院，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "人文科学研究院 教学科研区 教学科研"
  },
  {
    "id": "building-13818b1c",
    "officialId": "13818b1c7b0746e99e49eee18e88ccc5",
    "sourceType": "building",
    "name": "人字楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 51.84,
    "y": 10.717,
    "guide": "人字楼，教学科研区。",
    "mapDescription": "人字楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "人字楼 教学科研区 教学科研"
  },
  {
    "id": "slst",
    "officialId": "90e46c483efb4a6bb61aac4146bf7187",
    "sourceType": "building",
    "name": "生命学院",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 46.771,
    "y": 20.007,
    "guide": "生命学院，教学科研区。",
    "mapDescription": "生命学院，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "生命学院 教学科研区 教学科研"
  },
  {
    "id": "sbme",
    "officialId": "c813d9f099ae4730808a12ab76665261",
    "sourceType": "building",
    "name": "生医工学院",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 48.928,
    "y": 53.736,
    "guide": "生医工学院，教学科研区。",
    "mapDescription": "生医工学院，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "生医工学院 教学科研区 教学科研"
  },
  {
    "id": "ims",
    "officialId": "c333109b5216446084f36141178bddc5",
    "sourceType": "building",
    "name": "数学科学研究所",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 33.319,
    "y": 65.823,
    "guide": "数学科学研究所，教学科研区。",
    "mapDescription": "数学科学研究所，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "数学科学研究所 教学科研区 教学科研"
  },
  {
    "id": "library",
    "officialId": "e2473fa9855d45cbb5c5b8d15bc8b8f4",
    "sourceType": "building",
    "name": "图书馆",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 56.454,
    "y": 72.998,
    "guide": "图书馆，教学科研区。",
    "mapDescription": "图书馆，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "图书馆 教学科研区 教学科研"
  },
  {
    "id": "place-1bdc8674",
    "officialId": "1bdc8674323047019e9ef96c60177ed8",
    "sourceType": "place",
    "name": "图书馆",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 53.517,
    "y": 63.76,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "图书馆，教学科研区。",
    "mapDescription": "图书馆，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "图书馆 教学科研区 教学科研"
  },
  {
    "id": "spst-1",
    "officialId": "ded84a6dea0b457e9c7dc11a07f07534",
    "sourceType": "building",
    "name": "物质学院1号楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 34.073,
    "y": 42.919,
    "guide": "物质学院1号楼，教学科研区。",
    "mapDescription": "物质学院1号楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "物质学院1号楼 教学科研区 教学科研"
  },
  {
    "id": "spst-2",
    "officialId": "7414c5fbe7c34a08837882cfe1d4611a",
    "sourceType": "building",
    "name": "物质学院2号楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 22.835,
    "y": 46.83,
    "guide": "物质学院2号楼，教学科研区。",
    "mapDescription": "物质学院2号楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "物质学院2号楼 教学科研区 教学科研"
  },
  {
    "id": "spst-3",
    "officialId": "335e450978a74653a51c3b98fd5face1",
    "sourceType": "building",
    "name": "物质学院3号楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 16.251,
    "y": 50.104,
    "guide": "物质学院3号楼，教学科研区。",
    "mapDescription": "物质学院3号楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "物质学院3号楼 教学科研区 教学科研"
  },
  {
    "id": "spst-4",
    "officialId": "35af883db43a4fdda740867dcf15bdaf",
    "sourceType": "building",
    "name": "物质学院4号楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 34.314,
    "y": 50.863,
    "guide": "物质学院4号楼，教学科研区。",
    "mapDescription": "物质学院4号楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "物质学院4号楼 教学科研区 教学科研"
  },
  {
    "id": "spst-5",
    "officialId": "6f964a8f7e7842dcaa566c02e3efd5a9",
    "sourceType": "building",
    "name": "物质学院5号楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 29.838,
    "y": 53.9,
    "guide": "物质学院5号楼，教学科研区。",
    "mapDescription": "物质学院5号楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "物质学院5号楼 教学科研区 教学科研"
  },
  {
    "id": "spst-6",
    "officialId": "3daa8855730c44e884aa085c66f07410",
    "sourceType": "building",
    "name": "物质学院6号楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 25.874,
    "y": 52.804,
    "guide": "物质学院6号楼，教学科研区。",
    "mapDescription": "物质学院6号楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "物质学院6号楼 教学科研区 教学科研"
  },
  {
    "id": "spst-7",
    "officialId": "df01a02575b748e4b3a92d2c43265cfd",
    "sourceType": "building",
    "name": "物质学院7号楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 19.928,
    "y": 55.72,
    "guide": "物质学院7号楼，教学科研区。",
    "mapDescription": "物质学院7号楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "物质学院7号楼 教学科研区 教学科研"
  },
  {
    "id": "spst-8",
    "officialId": "a18b0cdd36dd46e79b49937779eddca2",
    "sourceType": "building",
    "name": "物质学院8号楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 25.047,
    "y": 57.569,
    "guide": "物质学院8号楼，教学科研区。",
    "mapDescription": "物质学院8号楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "物质学院8号楼 教学科研区 教学科研"
  },
  {
    "id": "place-d18cce07",
    "officialId": "d18cce070ff6498482e12767b7bace68",
    "sourceType": "place",
    "name": "信息学院",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 40.967,
    "y": 55.522,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "信息学院，教学科研区。",
    "mapDescription": "信息学院，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "信息学院 教学科研区 教学科研"
  },
  {
    "id": "sist-1",
    "officialId": "82807efc2a064e7a9dd37462c36f6263",
    "sourceType": "building",
    "name": "信息学院1号楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 38.522,
    "y": 50.263,
    "guide": "信息学院1号楼，教学科研区。",
    "mapDescription": "信息学院1号楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "信息学院1号楼 教学科研区 教学科研"
  },
  {
    "id": "sist-2",
    "officialId": "0e1be3485aa9405f958585eaa9ef1a7e",
    "sourceType": "building",
    "name": "信息学院2号楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 42.182,
    "y": 43.468,
    "guide": "信息学院2号楼，教学科研区。",
    "mapDescription": "信息学院2号楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "信息学院2号楼 教学科研区 教学科研"
  },
  {
    "id": "sist-3",
    "officialId": "cc7ff26a3d6a41f590d43770f319db18",
    "sourceType": "building",
    "name": "信息学院3号楼",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 51.366,
    "y": 42.904,
    "guide": "信息学院3号楼，教学科研区。",
    "mapDescription": "信息学院3号楼，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "信息学院3号楼 教学科研区 教学科研"
  },
  {
    "id": "ihuman",
    "officialId": "042bf0bcfc1545ceb59ea2d9df5ef7b7",
    "sourceType": "building",
    "name": "iHuman研究所",
    "area": "教学科研区",
    "category": "教学科研",
    "x": 52.21,
    "y": 11.204,
    "guide": "iHuman研究所，教学科研区。",
    "mapDescription": "iHuman研究所，教学科研区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "iHuman研究所 教学科研区 教学科研"
  },
  {
    "id": "cainiao-station-place",
    "officialId": "80ebccc280c548eaade204b8d3292698",
    "sourceType": "place",
    "name": "菜鸟驿站",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 79.585,
    "y": 43.295,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "菜鸟驿站，生活服务区。",
    "mapDescription": "菜鸟驿站，生活服务区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "菜鸟驿站 生活服务区 生活服务"
  },
  {
    "id": "building-e390ec90",
    "officialId": "e390ec90cae245d494970b411819a3b6",
    "sourceType": "building",
    "name": "纪念品店",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 67.174,
    "y": 50.011,
    "guide": "纪念品店，生活服务区。",
    "mapDescription": "纪念品店，生活服务区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "纪念品店 生活服务区 生活服务"
  },
  {
    "id": "place-78728cda",
    "officialId": "78728cdab57d4545b5d001dca8db0784",
    "sourceType": "place",
    "name": "纪念品专卖",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 66.617,
    "y": 50.027,
    "hostBuildingId": "building-e390ec90",
    "hostBuildingName": "纪念品店",
    "guide": "纪念品专卖，位于或靠近纪念品店。",
    "mapDescription": "纪念品专卖，位于或靠近纪念品店；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "纪念品专卖 生活服务区 生活服务 纪念品店"
  },
  {
    "id": "family-mart",
    "officialId": "0946b1b329a94459806cee67b155df39",
    "sourceType": "place",
    "name": "全家便利店",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 71.297,
    "y": 43.979,
    "hostBuildingId": "dorm-4",
    "hostBuildingName": "学生公寓4号楼",
    "guide": "全家便利店，位于或靠近学生公寓4号楼。",
    "mapDescription": "全家便利店，位于或靠近学生公寓4号楼；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "全家便利店 生活服务区 生活服务 学生公寓4号楼"
  },
  {
    "id": "bank-of-shanghai",
    "officialId": "6a1bae5c8ede4faaaf933be76a08465d",
    "sourceType": "building",
    "name": "上海银行",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 78.699,
    "y": 39.939,
    "guide": "上海银行，生活服务区。",
    "mapDescription": "上海银行，生活服务区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "上海银行 生活服务区 生活服务"
  },
  {
    "id": "place-e32fb679",
    "officialId": "e32fb6793fce48e697ee4b30933a007f",
    "sourceType": "place",
    "name": "上海银行",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 78.774,
    "y": 45.82,
    "hostBuildingId": "bank-of-shanghai",
    "hostBuildingName": "上海银行",
    "guide": "上海银行，生活服务区。",
    "mapDescription": "上海银行，生活服务区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "上海银行 生活服务区 生活服务 上海银行"
  },
  {
    "id": "bank-of-shanghai-atm-place",
    "officialId": "076e5a66ac484f3a81c3595ab0f56205",
    "sourceType": "place",
    "name": "上海银行ATM",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 49.938,
    "y": 66.221,
    "hostBuildingId": "library",
    "hostBuildingName": "图书馆",
    "guide": "上海银行ATM，位于或靠近图书馆。",
    "mapDescription": "上海银行ATM，位于或靠近图书馆；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "上海银行ATM 生活服务区 生活服务 图书馆"
  },
  {
    "id": "clinic-building",
    "officialId": "8227e54787b4491ab0bf9961af4fbf50",
    "sourceType": "building",
    "name": "卫生所",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 59.036,
    "y": 31.243,
    "guide": "卫生所，生活服务区。",
    "mapDescription": "卫生所，生活服务区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "卫生所 生活服务区 生活服务"
  },
  {
    "id": "print-room",
    "officialId": "2891773a8b6f4bde8b800d09d85bf66d",
    "sourceType": "place",
    "name": "文印室",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 62.649,
    "y": 61.073,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "文印室，生活服务区。",
    "mapDescription": "文印室，生活服务区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "文印室 生活服务区 生活服务"
  },
  {
    "id": "service-center-place",
    "officialId": "ce53c23ff2ae4c6fbda0781eab773ecb",
    "sourceType": "place",
    "name": "校园服务中心",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 58.483,
    "y": 41.747,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "校园服务中心，生活服务区。",
    "mapDescription": "校园服务中心，生活服务区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "校园服务中心 生活服务区 生活服务"
  },
  {
    "id": "barber",
    "officialId": "25250bbc37274eb69ff420fe47fc5ecf",
    "sourceType": "place",
    "name": "校园理发中心",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 69.217,
    "y": 32.876,
    "hostBuildingId": "dorm-2",
    "hostBuildingName": "学生公寓2号楼",
    "guide": "校园理发中心，位于或靠近学生公寓2号楼。",
    "mapDescription": "校园理发中心，位于或靠近学生公寓2号楼；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "校园理发中心 生活服务区 生活服务 学生公寓2号楼"
  },
  {
    "id": "student-affairs",
    "officialId": "57aad6d6bb9c4b3d9f91f781bebd31e3",
    "sourceType": "building",
    "name": "学生处",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 74.468,
    "y": 34.426,
    "guide": "学生处，生活服务区。",
    "mapDescription": "学生处，生活服务区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生处 生活服务区 生活服务"
  },
  {
    "id": "clinic-place",
    "officialId": "c678e4abfb4f402aa011fdeb60df559a",
    "sourceType": "place",
    "name": "医务室",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 61.416,
    "y": 29.093,
    "hostBuildingId": "clinic-building",
    "hostBuildingName": "卫生所",
    "guide": "医务室，位于或靠近卫生所。",
    "mapDescription": "医务室，位于或靠近卫生所；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "医务室 生活服务区 生活服务 卫生所"
  },
  {
    "id": "self-print",
    "officialId": "de9406b0fcef41a08443f8855f2cc8bf",
    "sourceType": "place",
    "name": "自助打印",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 47.355,
    "y": 60.201,
    "hostBuildingId": "teaching",
    "hostBuildingName": "教学中心",
    "guide": "自助打印，位于或靠近教学中心。",
    "mapDescription": "自助打印，位于或靠近教学中心；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "自助打印 生活服务区 生活服务 教学中心"
  },
  {
    "id": "service",
    "officialId": "70bba10b81b444ea8759b6427c654628",
    "sourceType": "building",
    "name": "H1,校园服务中心,309室 IT服务中心",
    "area": "生活服务区",
    "category": "生活服务",
    "x": 59.353,
    "y": 34.466,
    "guide": "H1,校园服务中心,309室 IT服务中心，生活服务区。",
    "mapDescription": "H1,校园服务中心,309室 IT服务中心，生活服务区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "H1,校园服务中心,309室 IT服务中心 生活服务区 生活服务"
  },
  {
    "id": "building-04efe709",
    "officialId": "04efe709b15541e4be9ad1d72bd63e19",
    "sourceType": "building",
    "name": "健身场",
    "area": "体育运动区",
    "category": "运动",
    "x": 87.164,
    "y": 51.959,
    "guide": "健身场，体育运动区。",
    "mapDescription": "健身场，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "健身场 体育运动区 运动"
  },
  {
    "id": "place-1def9a36",
    "officialId": "1def9a3660f24f00ad091c4f48ce0aeb",
    "sourceType": "place",
    "name": "健身场",
    "area": "体育运动区",
    "category": "运动",
    "x": 87.164,
    "y": 51.959,
    "hostBuildingId": "building-04efe709",
    "hostBuildingName": "健身场",
    "guide": "健身场，体育运动区。",
    "mapDescription": "健身场，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "健身场 体育运动区 运动 健身场"
  },
  {
    "id": "building-67a2a330",
    "officialId": "67a2a330debc4292bb768bff52e88e68",
    "sourceType": "building",
    "name": "篮球场",
    "area": "体育运动区",
    "category": "运动",
    "x": 84.228,
    "y": 54.53,
    "guide": "篮球场，体育运动区。",
    "mapDescription": "篮球场，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "篮球场 体育运动区 运动"
  },
  {
    "id": "place-161618a0",
    "officialId": "161618a0da314b2788ddfc8946e18c2a",
    "sourceType": "place",
    "name": "篮球场",
    "area": "体育运动区",
    "category": "运动",
    "x": 84.228,
    "y": 54.53,
    "hostBuildingId": "building-67a2a330",
    "hostBuildingName": "篮球场",
    "guide": "篮球场，体育运动区。",
    "mapDescription": "篮球场，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "篮球场 体育运动区 运动 篮球场"
  },
  {
    "id": "building-33115ddb",
    "officialId": "33115ddbc53547649ba73f5a89a95721",
    "sourceType": "building",
    "name": "排球场",
    "area": "体育运动区",
    "category": "运动",
    "x": 81.545,
    "y": 56.857,
    "guide": "排球场，体育运动区。",
    "mapDescription": "排球场，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "排球场 体育运动区 运动"
  },
  {
    "id": "place-dbd256d4",
    "officialId": "dbd256d44d1c4ad2a9bb31de435f2149",
    "sourceType": "place",
    "name": "排球场",
    "area": "体育运动区",
    "category": "运动",
    "x": 81.545,
    "y": 56.857,
    "hostBuildingId": "building-33115ddb",
    "hostBuildingName": "排球场",
    "guide": "排球场，体育运动区。",
    "mapDescription": "排球场，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "排球场 体育运动区 运动 排球场"
  },
  {
    "id": "stadium",
    "officialId": "dbe3b0a12e9845b389cddc3944ace241",
    "sourceType": "building",
    "name": "体育场",
    "area": "体育运动区",
    "category": "运动",
    "x": 85.987,
    "y": 61.651,
    "guide": "体育场，体育运动区。",
    "mapDescription": "体育场，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "体育场 体育运动区 运动"
  },
  {
    "id": "athletic",
    "officialId": "df290f76befc4c1eb3ba2cedb6c985c1",
    "sourceType": "building",
    "name": "体育馆",
    "area": "体育运动区",
    "category": "运动",
    "x": 75.9,
    "y": 40.98,
    "guide": "体育馆，体育运动区。",
    "mapDescription": "体育馆，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "体育馆 体育运动区 运动"
  },
  {
    "id": "place-035e4e3a",
    "officialId": "035e4e3af18e415a8496ee7017cb8b2d",
    "sourceType": "place",
    "name": "体育馆",
    "area": "体育运动区",
    "category": "运动",
    "x": 75.9,
    "y": 40.98,
    "hostBuildingId": "athletic",
    "hostBuildingName": "体育馆",
    "guide": "体育馆，体育运动区。",
    "mapDescription": "体育馆，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "体育馆 体育运动区 运动 体育馆"
  },
  {
    "id": "building-9267d351",
    "officialId": "9267d351830441fb84713b2dbc10ef25",
    "sourceType": "building",
    "name": "网球场",
    "area": "体育运动区",
    "category": "运动",
    "x": 58.725,
    "y": 21.041,
    "guide": "网球场，体育运动区。",
    "mapDescription": "网球场，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "网球场 体育运动区 运动"
  },
  {
    "id": "place-9b1fc653",
    "officialId": "9b1fc653f63a42f28dc63d35b26a07c4",
    "sourceType": "place",
    "name": "网球场",
    "area": "体育运动区",
    "category": "运动",
    "x": 58.725,
    "y": 21.041,
    "hostBuildingId": "building-9267d351",
    "hostBuildingName": "网球场",
    "guide": "网球场，体育运动区。",
    "mapDescription": "网球场，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "网球场 体育运动区 运动 网球场"
  },
  {
    "id": "place-e0e80c9f",
    "officialId": "e0e80c9f09804bd28f6ff65a7d394e20",
    "sourceType": "place",
    "name": "网球场",
    "area": "体育运动区",
    "category": "运动",
    "x": 58.725,
    "y": 21.041,
    "hostBuildingId": "building-9267d351",
    "hostBuildingName": "网球场",
    "guide": "网球场，体育运动区。",
    "mapDescription": "网球场，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "网球场 体育运动区 运动 网球场"
  },
  {
    "id": "building-3a541f1f",
    "officialId": "3a541f1f57154e7284db50fb5ee4bf10",
    "sourceType": "building",
    "name": "游泳馆",
    "area": "体育运动区",
    "category": "运动",
    "x": 66.369,
    "y": 16.216,
    "guide": "游泳馆，体育运动区。",
    "mapDescription": "游泳馆，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "游泳馆 体育运动区 运动"
  },
  {
    "id": "place-5ceab330",
    "officialId": "5ceab330cb934f43929b41a9d509f8cd",
    "sourceType": "place",
    "name": "游泳馆",
    "area": "体育运动区",
    "category": "运动",
    "x": 66.369,
    "y": 16.216,
    "hostBuildingId": "building-3a541f1f",
    "hostBuildingName": "游泳馆",
    "guide": "游泳馆，体育运动区。",
    "mapDescription": "游泳馆，体育运动区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "游泳馆 体育运动区 运动 游泳馆"
  },
  {
    "id": "place-a7e65a53",
    "officialId": "a7e65a5329684f209b471687ef016218",
    "sourceType": "place",
    "name": "运动场",
    "area": "体育运动区",
    "category": "运动",
    "x": 85.515,
    "y": 65.514,
    "hostBuildingId": "stadium",
    "hostBuildingName": "体育场",
    "guide": "运动场，位于或靠近体育场。",
    "mapDescription": "运动场，位于或靠近体育场；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "运动场 体育运动区 运动 体育场"
  },
  {
    "id": "faculty-apartment-1",
    "officialId": "ce3cc625afb04ad89ee754f2803ab91f",
    "sourceType": "building",
    "name": "教授公寓1号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 69.178,
    "y": 68.929,
    "guide": "教授公寓1号楼，生活住宿区。",
    "mapDescription": "教授公寓1号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "教授公寓1号楼 生活住宿区 住宿"
  },
  {
    "id": "faculty-apartment-2",
    "officialId": "027658990162450091ed9a5015aa9717",
    "sourceType": "building",
    "name": "教授公寓2号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 79.318,
    "y": 73.895,
    "guide": "教授公寓2号楼，生活住宿区。",
    "mapDescription": "教授公寓2号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "教授公寓2号楼 生活住宿区 住宿"
  },
  {
    "id": "faculty-apartment-3",
    "officialId": "fcc24b4351c949738935b29a11968e5c",
    "sourceType": "building",
    "name": "教授公寓3号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 85.15,
    "y": 78.203,
    "guide": "教授公寓3号楼，生活住宿区。",
    "mapDescription": "教授公寓3号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "教授公寓3号楼 生活住宿区 住宿"
  },
  {
    "id": "faculty-apartment-4",
    "officialId": "ac56d5e061e54f73998adecdff73b968",
    "sourceType": "building",
    "name": "教授公寓4号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 63.406,
    "y": 78.617,
    "guide": "教授公寓4号楼，生活住宿区。",
    "mapDescription": "教授公寓4号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "教授公寓4号楼 生活住宿区 住宿"
  },
  {
    "id": "faculty-apartment-5",
    "officialId": "491a728df0784c5ba99cc3df13325be7",
    "sourceType": "building",
    "name": "教授公寓5号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 75.09,
    "y": 83.023,
    "guide": "教授公寓5号楼，生活住宿区。",
    "mapDescription": "教授公寓5号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "教授公寓5号楼 生活住宿区 住宿"
  },
  {
    "id": "faculty-apartment-6",
    "officialId": "0861c5f7cf734a3fb80db2668d6a28e6",
    "sourceType": "building",
    "name": "教授公寓6号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 84.494,
    "y": 84.364,
    "guide": "教授公寓6号楼，生活住宿区。",
    "mapDescription": "教授公寓6号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "教授公寓6号楼 生活住宿区 住宿"
  },
  {
    "id": "building-5aae1afd",
    "officialId": "5aae1afd26364613a4c1e34971876e5a",
    "sourceType": "building",
    "name": "上海张江海科雅乐轩酒店",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 69.618,
    "y": 3.596,
    "guide": "上海张江海科雅乐轩酒店，生活住宿区。",
    "mapDescription": "上海张江海科雅乐轩酒店，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "上海张江海科雅乐轩酒店 生活住宿区 住宿"
  },
  {
    "id": "dorm-10",
    "officialId": "c7dec4f5551e487d92e9e4c434503218",
    "sourceType": "building",
    "name": "学生公寓10号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 76.438,
    "y": 63.813,
    "guide": "学生公寓10号楼，生活住宿区。",
    "mapDescription": "学生公寓10号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生公寓10号楼 生活住宿区 住宿"
  },
  {
    "id": "dorm-1",
    "officialId": "08935e62bb8944eb9d14e917475bd8d6",
    "sourceType": "building",
    "name": "学生公寓1号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 71.873,
    "y": 40.067,
    "guide": "学生公寓1号楼，生活住宿区。",
    "mapDescription": "学生公寓1号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生公寓1号楼 生活住宿区 住宿"
  },
  {
    "id": "dorm-2",
    "officialId": "870c648baede4d7695c9d6ba21b6941d",
    "sourceType": "building",
    "name": "学生公寓2号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 70.825,
    "y": 40.74,
    "guide": "学生公寓2号楼，生活住宿区。",
    "mapDescription": "学生公寓2号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生公寓2号楼 生活住宿区 住宿"
  },
  {
    "id": "dorm-3",
    "officialId": "e2d546c8f5594eb88b2fdc40bdc9a4af",
    "sourceType": "building",
    "name": "学生公寓3号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 70.467,
    "y": 45.984,
    "guide": "学生公寓3号楼，生活住宿区。",
    "mapDescription": "学生公寓3号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生公寓3号楼 生活住宿区 住宿"
  },
  {
    "id": "dorm-4",
    "officialId": "bcb08e41d2d04acf83bbaae4a21196ae",
    "sourceType": "building",
    "name": "学生公寓4号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 70.588,
    "y": 47.938,
    "guide": "学生公寓4号楼，生活住宿区。",
    "mapDescription": "学生公寓4号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生公寓4号楼 生活住宿区 住宿"
  },
  {
    "id": "dorm-5",
    "officialId": "f79abaa2ff4447aa8a26c63533c0d0dc",
    "sourceType": "building",
    "name": "学生公寓5号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 70.515,
    "y": 53.778,
    "guide": "学生公寓5号楼，生活住宿区。",
    "mapDescription": "学生公寓5号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生公寓5号楼 生活住宿区 住宿"
  },
  {
    "id": "dorm-6",
    "officialId": "3f62d5cd197f47f786b55b933a1c7154",
    "sourceType": "building",
    "name": "学生公寓6号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 67.168,
    "y": 60.709,
    "guide": "学生公寓6号楼，生活住宿区。",
    "mapDescription": "学生公寓6号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生公寓6号楼 生活住宿区 住宿"
  },
  {
    "id": "dorm-7",
    "officialId": "6b98ac6446604b2ea213ed8bf0a1e54b",
    "sourceType": "building",
    "name": "学生公寓7号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 74.158,
    "y": 53.267,
    "guide": "学生公寓7号楼，生活住宿区。",
    "mapDescription": "学生公寓7号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生公寓7号楼 生活住宿区 住宿"
  },
  {
    "id": "dorm-8",
    "officialId": "a747029d40c840d2860b01d14be486dd",
    "sourceType": "building",
    "name": "学生公寓8号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 76.405,
    "y": 50.102,
    "guide": "学生公寓8号楼，生活住宿区。",
    "mapDescription": "学生公寓8号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生公寓8号楼 生活住宿区 住宿"
  },
  {
    "id": "dorm-9",
    "officialId": "73374de7e44541c99a1bb59f68d9df1f",
    "sourceType": "building",
    "name": "学生公寓9号楼",
    "area": "生活住宿区",
    "category": "住宿",
    "x": 75.971,
    "y": 60.552,
    "guide": "学生公寓9号楼，生活住宿区。",
    "mapDescription": "学生公寓9号楼，生活住宿区；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生公寓9号楼 生活住宿区 住宿"
  },
  {
    "id": "place-5fc99e4d",
    "officialId": "5fc99e4d9bde4d03bd62c914c066ff93",
    "sourceType": "place",
    "name": "(南川线)华夏中路殷家浜路",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 52.961,
    "y": 99.65,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "(南川线)华夏中路殷家浜路，出入口与交通。",
    "mapDescription": "(南川线)华夏中路殷家浜路，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "(南川线)华夏中路殷家浜路 出入口与交通 出入口交通"
  },
  {
    "id": "place-16423562",
    "officialId": "164235623608429383432866209f6098",
    "sourceType": "place",
    "name": "(浦东25路)金科路中科路",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 100,
    "y": 37.938,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "(浦东25路)金科路中科路，出入口与交通。",
    "mapDescription": "(浦东25路)金科路中科路，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "(浦东25路)金科路中科路 出入口与交通 出入口交通"
  },
  {
    "id": "place-7ab31906",
    "officialId": "7ab31906eede48c9a3ca83196cb03688",
    "sourceType": "place",
    "name": "(浦东58路)海科路金科路",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 92.827,
    "y": 4.249,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "(浦东58路)海科路金科路，出入口与交通。",
    "mapDescription": "(浦东58路)海科路金科路，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "(浦东58路)海科路金科路 出入口与交通 出入口交通"
  },
  {
    "id": "place-56b3c18a",
    "officialId": "56b3c18a230f4afcb9da0913786538cd",
    "sourceType": "place",
    "name": "(浦东58路)海科路科苑路",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 62.025,
    "y": 3.048,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "(浦东58路)海科路科苑路，出入口与交通。",
    "mapDescription": "(浦东58路)海科路科苑路，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "(浦东58路)海科路科苑路 出入口与交通 出入口交通"
  },
  {
    "id": "place-316aa14a",
    "officialId": "316aa14a65ee463999df5517547d1ad0",
    "sourceType": "place",
    "name": "(浦东58路)环科路金科路",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 88.487,
    "y": 81.119,
    "hostBuildingId": "southeast-gate",
    "hostBuildingName": "上海科技大学东南门(环科路199号)",
    "guide": "(浦东58路)环科路金科路，位于或靠近上海科技大学东南门(环科路199号)。",
    "mapDescription": "(浦东58路)环科路金科路，位于或靠近上海科技大学东南门(环科路199号)；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "(浦东58路)环科路金科路 出入口与交通 出入口交通 上海科技大学东南门(环科路199号)"
  },
  {
    "id": "place-0436da9b",
    "officialId": "0436da9b54784a1198525a987dd7a09c",
    "sourceType": "place",
    "name": "车库出入口",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 78.79,
    "y": 23.653,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "车库出入口，出入口与交通。",
    "mapDescription": "车库出入口，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "车库出入口 出入口与交通 出入口交通"
  },
  {
    "id": "place-04496d91",
    "officialId": "04496d91aa5d431a852252ed5fda6bd8",
    "sourceType": "place",
    "name": "车库出入口",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 77.556,
    "y": 56.806,
    "hostBuildingId": "dorm-10",
    "hostBuildingName": "学生公寓10号楼",
    "guide": "车库出入口，位于或靠近学生公寓10号楼。",
    "mapDescription": "车库出入口，位于或靠近学生公寓10号楼；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "车库出入口 出入口与交通 出入口交通 学生公寓10号楼"
  },
  {
    "id": "place-1382d8df",
    "officialId": "1382d8df1ebd4da08dc6dd6ce7c7c2b1",
    "sourceType": "place",
    "name": "车库出入口",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 55.202,
    "y": 22.145,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "车库出入口，出入口与交通。",
    "mapDescription": "车库出入口，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "车库出入口 出入口与交通 出入口交通"
  },
  {
    "id": "place-18165b05",
    "officialId": "18165b05d45646888ae63c76ac10722c",
    "sourceType": "place",
    "name": "车库出入口",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 72.868,
    "y": 10.622,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "车库出入口，出入口与交通。",
    "mapDescription": "车库出入口，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "车库出入口 出入口与交通 出入口交通"
  },
  {
    "id": "place-435c1c63",
    "officialId": "435c1c6331104bfda6e0dd3366a6580a",
    "sourceType": "place",
    "name": "车库出入口",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 81.651,
    "y": 70.645,
    "hostBuildingId": "faculty-apartment-2",
    "hostBuildingName": "教授公寓2号楼",
    "guide": "车库出入口，位于或靠近教授公寓2号楼。",
    "mapDescription": "车库出入口，位于或靠近教授公寓2号楼；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "车库出入口 出入口与交通 出入口交通 教授公寓2号楼"
  },
  {
    "id": "place-8137aa89",
    "officialId": "8137aa89cca1437fa04632465de2956a",
    "sourceType": "place",
    "name": "车库出入口",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 44.471,
    "y": 8.546,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "车库出入口，出入口与交通。",
    "mapDescription": "车库出入口，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "车库出入口 出入口与交通 出入口交通"
  },
  {
    "id": "place-9a5774fc",
    "officialId": "9a5774fc529f413f9ae3de1b9cdc705c",
    "sourceType": "place",
    "name": "车库出入口",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 9.177,
    "y": 56.761,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "车库出入口，出入口与交通。",
    "mapDescription": "车库出入口，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "车库出入口 出入口与交通 出入口交通"
  },
  {
    "id": "place-31b3c869",
    "officialId": "31b3c869c10141e49acfcae9a55dbfff",
    "sourceType": "place",
    "name": "地铁13号线中科路站",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 100,
    "y": 31.016,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "地铁13号线中科路站，出入口与交通。",
    "mapDescription": "地铁13号线中科路站，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "地铁13号线中科路站 出入口与交通 出入口交通"
  },
  {
    "id": "north-gate",
    "officialId": "cf81ca1c074245e3b501121765e9fbd8",
    "sourceType": "building",
    "name": "上海科技大学北门(海科路230号)",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 36.026,
    "y": 6.711,
    "guide": "上海科技大学北门(海科路230号)，出入口与交通。",
    "mapDescription": "上海科技大学北门(海科路230号)，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "上海科技大学北门(海科路230号) 出入口与交通 出入口交通"
  },
  {
    "id": "east-gate",
    "officialId": "c9e29e1ba374411bbbda3ee581a73c64",
    "sourceType": "building",
    "name": "上海科技大学东门(中科路1号)",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 83.288,
    "y": 29.304,
    "guide": "上海科技大学东门(中科路1号)，出入口与交通。",
    "mapDescription": "上海科技大学东门(中科路1号)，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "上海科技大学东门(中科路1号) 出入口与交通 出入口交通"
  },
  {
    "id": "southeast-gate",
    "officialId": "18dccb41f7fb4464bf6ca1e457b2be98",
    "sourceType": "building",
    "name": "上海科技大学东南门(环科路199号)",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 89.243,
    "y": 78.77,
    "guide": "上海科技大学东南门(环科路199号)，出入口与交通。",
    "mapDescription": "上海科技大学东南门(环科路199号)，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "上海科技大学东南门(环科路199号) 出入口与交通 出入口交通"
  },
  {
    "id": "south-gate",
    "officialId": "6cccd83bc8554dfcadd9a1a226cd91ca",
    "sourceType": "building",
    "name": "上海科技大学南门(华夏中路393号)",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 55.267,
    "y": 95.538,
    "guide": "上海科技大学南门(华夏中路393号)，出入口与交通。",
    "mapDescription": "上海科技大学南门(华夏中路393号)，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "上海科技大学南门(华夏中路393号) 出入口与交通 出入口交通"
  },
  {
    "id": "west-gate",
    "officialId": "bf9445e8e352431984e9176c1eb6bd78",
    "sourceType": "building",
    "name": "上海科技大学西门(集慧路249号)",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 4.593,
    "y": 57.77,
    "guide": "上海科技大学西门(集慧路249号)，出入口与交通。",
    "mapDescription": "上海科技大学西门(集慧路249号)，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "上海科技大学西门(集慧路249号) 出入口与交通 出入口交通"
  },
  {
    "id": "school-shuttle",
    "officialId": "dddd4057102b4c2da95b56e7ed9d875e",
    "sourceType": "place",
    "name": "学校班车",
    "area": "出入口与交通",
    "category": "出入口交通",
    "x": 79.962,
    "y": 56.665,
    "hostBuildingId": "",
    "hostBuildingName": "",
    "guide": "学校班车，出入口与交通。",
    "mapDescription": "学校班车，出入口与交通；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学校班车 出入口与交通 出入口交通"
  },
  {
    "id": "building-1f043d2c",
    "officialId": "1f043d2c3d214561a0d4e3fb9268721e",
    "sourceType": "building",
    "name": "会议中心",
    "area": "校内地点",
    "category": "校内地点",
    "x": 72.401,
    "y": 16.822,
    "guide": "会议中心，校内地点。",
    "mapDescription": "会议中心，校内地点；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "会议中心 校内地点 校内地点"
  },
  {
    "id": "building-f3f53eeb",
    "officialId": "f3f53eebc38742cbb402414c935c05bd",
    "sourceType": "building",
    "name": "行政中心",
    "area": "校内地点",
    "category": "校内地点",
    "x": 34.066,
    "y": 76.78,
    "guide": "行政中心，校内地点。",
    "mapDescription": "行政中心，校内地点；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "行政中心 校内地点 校内地点"
  },
  {
    "id": "building-ecdba91f",
    "officialId": "ecdba91f46c34d25ab920be789610eda",
    "sourceType": "building",
    "name": "学生活动中心",
    "area": "校内地点",
    "category": "校内地点",
    "x": 73.895,
    "y": 36.464,
    "guide": "学生活动中心，校内地点。",
    "mapDescription": "学生活动中心，校内地点；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "学生活动中心 校内地点 校内地点"
  },
  {
    "id": "h2-student-innovation",
    "officialId": "025af73a7496470fbde898016fc93784",
    "sourceType": "building",
    "name": "H2楼,学生科创中心",
    "area": "校内地点",
    "category": "校内地点",
    "x": 58.979,
    "y": 52.673,
    "guide": "H2楼,学生科创中心，校内地点。",
    "mapDescription": "H2楼,学生科创中心，校内地点；可补充入口、楼层、靠窗/靠路侧、附近标志物等细节。",
    "searchableText": "H2楼,学生科创中心 校内地点 校内地点"
  }
];

export const locationAliases = {
  "spst": "spst-1",
  "sist": "sist-1",
  "dorms": "dorm-1",
  "campus": "service",
  "food": "food-court",
  "canteen": "food-court",
  "family": "family-mart",
  "family-mart": "family-mart"
};

export const campusMapMeta = {
  "source": "https://map.shanghaitech.edu.cn/",
  "buildingCount": 65,
  "serviceCount": 44,
  "locationCount": 109,
  "projection": "official-baidu-polygons-to-3d-screenshot-anchors",
  "generatedFrom": "官方建筑与服务点数据 + 2026-07-12 3D地图截图锚点校准",
  "imageCalibration": {
    "method": "local-anchor-displacement",
    "targetImage": "屏幕截图 2026-07-12 002039.png",
    "imageWidth": 2125,
    "imageHeight": 1363,
    "imageAspectRatio": "2125/1363",
    "anchorCount": 30,
    "shapeSource": "official archite_entity.position polygons from https://map.shanghaitech.edu.cn/",
    "regionalCorrection": {
      "reason": "User-reported upward drift checked against official map positions on 2026-07-12",
      "affectedGroups": [
        "School of Entrepreneurship and Management",
        "Administrative Center",
        "Teaching Center",
        "Library",
        "Student Apartments",
        "Faculty Apartments"
      ],
      "offsetsPercent": {
        "coreAcademicWest": {
          "dy": 5.2
        },
        "studentApartments": {
          "dy": 4.4
        },
        "facultyApartments": {
          "dy": 4
        }
      }
    },
    "horizontalCorrection": {
      "reason": "User-reported left drift checked against official ShanghaiTech map on 2026-07-12",
      "dx": 1.8,
      "appliedTo": [
        "campusMapOutline",
        "campusMapLocations",
        "mapShapes",
        "campusMapImageBoundaries"
      ]
    }
  },
  "imageBoundaryCount": 65
};
